[package]
name = "language"
authors = ["qzvk <reisuo@protonmail.com>"]
version = "0.1.0"
edition = "2021"
description = "Interpreter for an experimental programming language."
license = "MIT OR Apache-2.0"
