[package]
name = "ir"
authors = ["qzvk <reisuo@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
parser = { path = "../parser" }
lexer = { path = "../lexer" }
